header_logo_url: /images/misf_logo.svg
header_logo_text: Miscellaneous Insecta Species File
header_links:
  - label: Home
    link: /

  - label: Search DwC
    link: /resources/tw/filter/dwc_otus

  - label: About
    link: /about
