header_logo_url: /images/misf_logo.svg
header_logo_text: Miscellaneous Insecta Species File
header_links:
  - label: Home
    link: /

  - label: News
    link: /news
    
  - label: Bibliography
    link: /resources/tw/filter/bibliography
    
  - label: Search DwC
    link: /resources/tw/filter/dwc_otus

  - label: Recent
    link: /recent

  - label: About
    link: /about
