---
project_name: 'Miscellaneous Insecta Species File'
project_citation: 'Miscellaneous Insecta Species File'
project_authors: 'Hopkins, H.'
project_url: 'https://misc.speciesfile.org'
project_old_url: 'http://grylloblattodea.archive.speciesfile.org.'
contact_email: 'cockroachdoc@gmail.com'
