---
project_name: 'Miscellaneous Insecta Species File'
project_citation: 'Miscellaneous Insecta Species File'
project_authors: 'Hopkins, H.'
project_url: 'https://grylloblattodea.speciesfile.org.'
project_old_url: 'http://grylloblattodea.archive.speciesfile.org.'
focal_taxon: 'grylloblattodea'
focal_taxon_common_name: 'ice crawlers'
contact_email: 'cockroachdoc@gmail.com'
